/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id 'java'
    id 'maven-publish'
}

repositories {
    mavenLocal()
    maven {
        url = uri('https://hub.spigotmc.org/nexus/content/repositories/snapshots/')
    }

    maven {
        url = uri('https://maven.enginehub.org/repo/')
    }

    maven {
        url = uri('https://repo.maven.apache.org/maven2/')
    }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.20-R0.1-SNAPSHOT'
    compileOnly 'com.sk89q.worldedit:worldedit-bukkit:7.2.0-SNAPSHOT'
}

group = 'me.daddychurchill'
version = '4.060'
description = 'CityWorld'

sourceCompatibility = 17
targetCompatibility = 17

publishing {
    publications {
        maven(MavenPublication) {
            from(components.java)
        }
    }
}

tasks {
    jar {
        enabled = true
    }
    
    finalizedBy {
        dependsOn(copyJarToBin)
    }
}

compileJava.options.encoding = 'UTF-8'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

task copyJarToBin {
    doLast {
        def outputDir = System.getProperty('os.name').toLowerCase().contains('win') ? 
            'C:/Plugins/output' : 
            '/home/rena/Schreibtisch/Plugins/output'

        copy {
            from "build/libs/${project.name}-${project.version}.jar"
            into outputDir
            rename { String fileName ->
                fileName.replace("-$project.version", "")
            }
        }
    }
}

build.finalizedBy publishToMavenLocal
